GamesHaven/GamesHaven/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("games/", include("games.urls")),
    path("publishers/", include("publishers.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

GamesHaven/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('contact/', views.contact_view, name="contact_view"),
    path("mode/<mode>/", views.mode_view, name="mode_view"),
    path("test/params/<int:param1>/<param2>/", views.test_params_view, name="test_params_view")
]

GamesHaven/publishers/urls.py
from django.urls import path
from . import views

app_name = "publishers"

urlpatterns = [
    path("add/", views.add_publisher_view, name="add_publisher_view"),
    path("all/", views.all_publishers_view, name="all_publishers_view"),
    path("<publisher_id>/", views.detail_publisher_view, name="detail_publisher_veiw"),
]

GamesHaven/publishers/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=1024)
    description = models.TextField()
    image = models.ImageField(upload_to="publishers_images/", default="publishers_images/default.jpg")

GamesHaven/publishers/forms.py
from django import forms
from .models import Publisher

class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = "__all__"

GamesHaven/publishers/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import Publisher
from .forms import PublisherForm
from games.models import Game

# Create your views here.
def add_publisher_view(request: HttpRequest):
    if request.method == "POST":
        publisher_form = PublisherForm(request.POST, request.FILES)
        if publisher_form.is_valid():
            publisher_form.save()
            return redirect("publishers:all_publishers_view")
        else:
            print("form error: ", PublisherForm.errors)

    return render(request, "publishers/add.html")


def all_publishers_view(request: HttpRequest):
    publishers = Publisher.objects.all()

    return render(request, "publishers/all.html", {"publishers": publishers})

def detail_publisher_view(request: HttpRequest, publisher_id: int):
    publisher = Publisher.objects.get(pk=publisher_id)

    return render(request, "publishers/detail.html", {"publisher": publisher})

GamesHaven/publishers/templates/publishers/add.html
{% extends 'main/base.html' %}


{% block title %}Add Publisher{% endblock %}

{% block content %}
<h1>Add a Publisher</h1>

<div class="row">

    <div class="col-6">

        <form class="d-flex flex-column gap-2" action="{% url 'publishers:add_publisher_view' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" placeholder="Name" name="name" class="form-control" required minlength="5" maxlength="512"/>
            <textarea placeholder="Description" name="description" class="form-control" required></textarea>
            <input type="file" name="image" class="form-control" required accept="image/*"/>
            <input type="submit" value="Add Publisher" class="btn btn-primary" />
        </form>

    </div>

</div>


{% endblock %}

GamesHaven/publishers/templates/publishers/all.html
{% extends 'main/base.html' %}


{% block title %}Add Publisher{% endblock %}

{% block content %}
<h1>All Publishers</h1>
<div class="container">
    <div class="row mt-2 row-cols-1 row-cols-md-3 g-4">
        {% for publisher in publishers %}
        <div class="col">
            <div class="justify-content-start align-items-start h-100 p-4 shadow gap-2">
                <div>
                    <img src="{{ publisher.image.url }}" alt="{{ publisher.name }}" class="w-100 poster-thumb object-fit-contain">
                </div>
                <div>{{ publisher.name }}</div>
                <a href="#">
                    <div class="d-flex justify-content-between">
                    
                        <span>More</span>
                        <span class="material-symbols-outlined text-fxl">arrow_forward</span>
                    
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>

</div>


{% endblock %}

GamesHaven/publishers/templates/publishers/detail.html
{% extends 'main/base.html' %}


{% block title %}Publisher Details{% endblock %}

{% block content %}
<h1>{{ publisher.name }}</h1>

<div class="container">
    <div class="row">
        <div class="col">
            <div class="d-flex flex-column p-4 gap-2 shadow">
                <img src="{{publisher.image.url}}" alt="{{ publisher.name }}" class="w-100">
                <div>
                    <p>{{ publisher.description }}</p>
                </div>
            </div>
        </div>
    </div>
    
</div>



{% endblock %}