GamesHaven/GamesHaven/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("games/", include("games.urls")),
    path("publishers/", include("publishers.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

GamesHaven/games/urls.py
from django.urls import path
from . import views


app_name = "games"

urlpatterns = [
    path("create/", views.create_game_view, name="create_game_view"),
    path("detail/<game_id>/", views.game_detail_view, name="game_detail_view"),
    path("update/<game_id>/", views.game_update_view, name="game_update_view"),
    path("delete/<game_id>/", views.game_delete_view, name="game_delete_view"),
    path("all/", views.all_games_view, name="all_games_view"),
    path("search/", views.search_games_view, name="search_games_view"),
    path("add_review/<game_id>/", views.add_review_view, name="add_review_view"),
]

GamesHaven/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('contact/', views.contact_view, name="contact_view"),
    path("mode/<mode>/", views.mode_view, name="mode_view"),
    path("test/params/<int:param1>/<param2>/", views.test_params_view, name="test_params_view")
]

GamesHaven/games/models.py
from django.db import models

# Create your models here.

# create category model -- many to many relationship
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Game(models.Model):

    class RatingChoices(models.IntegerChoices):
        STAR1 = 1, "One Star"
        STAR2 = 2, "Two Stars"
        STAR3 = 3, "Three Stars"
        STAR4 = 4, "Four Stars"
        STAR5 = 5, "Five Stars"

    title = models.CharField(max_length=1024)
    description = models.TextField()
    publisher = models.CharField(max_length=256)
    rating = models.SmallIntegerField(choices=RatingChoices.choices)
    release_date = models.DateField()
    poster = models.ImageField(upload_to="images/", default="images/default.jpg")
    # link the Game with Category model -- many to many relationship
    categories = models.ManyToManyField(Category)

    # defines the string representation of an instance of a model using dunder function
    def __str__(self) -> str:
        return self.title

class Review(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    name = models.CharField(max_length=1024)
    comment = models.TextField()
    rating = models.SmallIntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    # defines the string representation of an instance of a model using dunder function
    def __str__(self) -> str:
        return f"{self.name} on {self.game.title}"

GamesHaven/games/forms.py
from django import forms
from games.models import Game

# Create the form class.
class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = "__all__"
        widgets = {
            'title' : forms.TextInput({"class" : "form-control"})
        }

GamesHaven/games/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse

from .models import Game, Review, Category
from .forms import GameForm

# Create your views here.

def create_game_view(request:HttpRequest):

    game_form = GameForm()

    # define categories so we can pass it as context
    categories = Category.objects.all()

    if request.method == "POST":
        # game_form = GameForm(request.POST, request.FILES)
        # if game_form.is_valid():
        #     game_form.save()
        #     return redirect('main:home_view')
        # else:
        #     print("not valid form", game_form.errors)

        new_game = Game(title=request.POST["title"], description=request.POST["description"], publisher=request.POST["publisher"], rating=request.POST["rating"], release_date=request.POST["release_date"], poster=request.FILES["poster"])
        new_game.save()
        # use set to add categories (many to many field) to the new_game object
        new_game.categories.set(request.POST.getlist("categories"))

        return redirect('main:home_view')
    

    return render(request, "games/create.html", {"game_form":game_form,"RatingChoices": reversed(Game.RatingChoices.choices), "categories": categories})


def game_detail_view(request:HttpRequest, game_id:int):

    game = Game.objects.get(pk=game_id)

    reviews = Review.objects.filter(game=game)

    return render(request, 'games/game_detail.html', {"game" : game, "reviews": reviews})


def game_update_view(request:HttpRequest, game_id:int):

    game = Game.objects.get(pk=game_id)
    categories = Category.objects.all()

    if request.method == "POST":
        game.title = request.POST["title"]
        game.description = request.POST["description"]
        game.release_date = request.POST["release_date"]
        game.publisher = request.POST["publisher"]
        game.rating = request.POST["rating"]
        if "poster" in request.FILES: game.poster = request.FILES["poster"]
        game.save()
        # use set to update category field (many to many)
        game.categories.set(request.POST.getlist("categories"))


        return redirect("games:game_detail_view", game_id=game.id)

    return render(request, "games/game_update.html", {"game":game, "categories": categories})


def game_delete_view(request:HttpRequest, game_id:int):

    game = Game.objects.get(pk=game_id)
    game.delete()

    return redirect("main:home_view")


def all_games_view(request:HttpRequest):
    #games = Game.objects.filter(rating__gte=3).order_by("-release_date")
    #games = Game.objects.filter(rating__gte=3).exclude(title__contains="Legends").order_by("-release_date")
    games = Game.objects.all().order_by("-release_date")

    #results count
    print(games.count())

    return render(request, "games/all_games.html", {"games":games})


def search_games_view(request:HttpRequest):

    if "search" in request.GET and len(request.GET["search"]) >= 3:
        games = Game.objects.filter(title__contains=request.GET["search"])

        if "order_by" in request.GET and request.GET["order_by"] == "rating":
            games = games.order_by("-rating")
        elif "order_by" in request.GET and request.GET["order_by"] == "release_date":
            games = games.order_by("-release_date")
    else:
        games = []


    return render(request, "games/search_games.html", {"games" : games})

def add_review_view(request: HttpRequest, game_id: int):
    if request.method == "POST":
        game_object = Game.objects.get(pk=game_id)
        new_review = Review(game=game_object, name=request.POST["name"], comment=request.POST["comment"], rating=request.POST["rating"])
        new_review.save()

    return redirect("games:game_detail_view", game_id=game_id)

GamesHaven/games/templates/games/all_games.html
{% extends 'main/base.html' %}


{% block title %}Create New Game{% endblock %}

{% block content %}
<h1>Games</h1>

{% include 'games/components/cards_list.html' %}

{% endblock %}

GamesHaven/games/templates/games/create.html
{% extends 'main/base.html' %}


{% block title %}Create New Game{% endblock %}

{% block content %}
<h1>Create Game</h1>

<div class="row">

    <div class="col-6">

        <form class="d-flex flex-column gap-2" action="{% url 'games:create_game_view' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" placeholder="Title" name="title" class="form-control" required minlength="5" maxlength="512"/>
            <textarea placeholder="Description" name="description" class="form-control" required></textarea>
            <input type="text" placeholder="Publisher" name="publisher" class="form-control" required />

            <div class="d-flex gap-2 align-items-center">
                <h5 class="m-0 p-0">Rating: </h5>
                <div class="rate">
                    {% for val, label in RatingChoices %}
                        <input type="radio" id="{{val}}" name="rating" value="{{val}}" required/>
                        <label for="{{val}}" title="text">{{label}}</label>
                    {% endfor %}
                </div>
            </div>

            <input type="date" name="release_date" class="form-control" required/>

            <input type="file" name="poster" class="form-control" required accept="image/*"/>

            <!-- categories checkboxes -->
             <h5 class="mt-2">Category</h5>
             <div class="d-flex gap-2 mb-2">
                 {% for category in categories %}
                    <input class="form-check-input" type="checkbox" name="categories" value="{{ category.id }}" id="category-{{ category.id }}">
                    <label class="form-check-label" for="category-{{ category.id }}">{{ category.name }}</label>
                 {% endfor %}
             </div>

            <input type="submit" value="Create Game" class="btn btn-primary" />

        </form>


    </div>

</div>


{% endblock %}

GamesHaven/games/templates/games/game_detail.html
{% extends 'main/base.html' %}


{% block title %}Create New Game{% endblock %}

{% block content %}
<h1>{{game.title}}</h1>

<div class="row">

    <div class="col">
        <div class="d-flex flex-column gap-2">
            <div class="d-flex justify-content-between">
                <h5>{{game.publisher}}</h5>
                <h6>{{game.release_date}}</h6>
            </div>
            <!-- game category -->
             <div class="d-flex gap-2">
              {% for category in game.categories.all %}
                <h6 class="category-{{ category }} p-1 px-3 rounded-pill text-white">{{ category }}</h6>
              {% endfor %}
             </div>
            <img src="{{ game.poster.url }}" class="w-100" />
            <div class="d-flex justify-content-end gap-2">
                <a href="{% url 'games:game_update_view' game.id %}" class="btn btn-primary">update</a>
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">delete</button>
            </div>
            <p>{{ game.description }}</p>
        </div>
    </div>

</div>

<!-- reviews -->
<h2 class="mt-5">Comments ({{reviews.count}})</h2>
{% for review in reviews %}
<div class="d-flex flex-column gap-2 p-4 shadow">
  <h4>{{ review.name }}</h4>
  <p>{{ review.comment }}</p>
  <p class="text-muted">{{ review.created_at }}</p>
</div>
{% endfor %}

<hr />
<!-- review form -->
 {% if reviews.count == 0 %}
  <h2 class="mt-5">Be first to comment</h2>
 {% else %}
  <h2 class="mt-5">Add a comment</h2>
 {% endif %}
<form class="d-flex flex-column gap-2" action="{% url 'games:add_review_view' game.id %}" method="post">
  {% csrf_token %}
  <input class="form-control" type="text" name="name" placeholder="Your name" required />
  <textarea class="form-control" name="comment" placeholder="Your comment" required></textarea>
  <select class="form-select" name="rating">
    <option value="" required>Rating</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
  </select>
  <input class="btn btn-primary" type="submit" />
</form>

<!-- Button trigger modal -->

  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Game</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are You sure you want to delete {{game.title}} ?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <a href="{% url 'games:game_delete_view' game.id %}" class="btn btn-danger">delete</a>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

GamesHaven/games/templates/games/game_update.html
{% extends 'main/base.html' %}


{% block title %}Create New Game{% endblock %}

{% block content %}
<h1>Update {{ game.title }}</h1>

<div class="row">

    <div class="col-6">

        <form class="d-flex flex-column gap-2" action="{% url 'games:game_update_view' game.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" placeholder="Title" name="title" class="form-control" value="{{game.title}}"/>
            <textarea placeholder="Description" name="description" class="form-control">{{game.description}}</textarea>
            <input type="text" placeholder="Publisher" name="publisher" class="form-control" value="{{game.publisher}}"/>
            <select class="form-select" name="rating">
                <option >Rating</option>
                <option value="1" {% if game.rating == 1 %}selected{% endif %}>One</option>
                <option value="2" {% if game.rating == 2 %}selected{% endif %}>Two</option>
                <option value="3" {% if game.rating == 3 %}selected{% endif %}>Three</option>
                <option value="4" {% if game.rating == 4 %}selected{% endif %}>Four</option>
                <option value="5" {% if game.rating == 5 %}selected{% endif %}>Five</option>
              </select>
            <input type="date" name="release_date" class="form-control" value="{{game.release_date.isoformat}}"/>

            <div class="row">
                <div class="col-3">
                    <img src="{{game.poster.url}}" class="w-100" />
                </div>
                <div class="col">
                    <input type="file" name="poster" class="form-control"/>
                    <!-- category -->
                    <h6 class="pt-3">Category:</h6>
                    <div class="d-flex gap-2 mb-2">
                        {% for category in categories %}
                            <input class="form-check-input" name="categories" type="checkbox" id="category-{{ category.id }}" value="{{ category.id }}" />
                            <label class="form-check-label" for="category-{{ category.id }}">{{ category.name }}</label>
                        {% endfor %}
                    </div>
                </div>
            </div>
        
            <input type="submit" value="update Game" class="btn btn-primary" />

        </form>


    </div>

</div>

{% endblock %}

GamesHaven/games/templates/games/search_games.html
{% extends 'main/base.html' %}


{% block title %}Create New Game{% endblock %}

{% block content %}
{% if games %}
<h1>Search Results ({{games.count}})</h1>
<h5>results for: {{request.GET.search}}</h5>
<div class="d-flex justify-content-end">
    <form action="{% url 'games:search_games_view' %}" method="GET" >

        <div class="d-flex gap-3">
            <input type="search" class="form-control" value="{{request.GET.search}}" name="search" required />
            <select name="order_by" class="form-select">
                <option value="">Order By</option>
                <option value="rating" {% if request.GET.order_by == 'rating'%} selected {% endif %}>Top Rating</option>
                <option value="release_date" {% if request.GET.order_by == 'release_date'%} selected {% endif %}>Release Rate</option>
            </select>
    
            <input type="submit" value="apply" class="btn btn-primary"/>
        </div>

    </form>
</div>

{% else %}
<p class="bg-warning p-3 rounded">No results found for your search "{{request.GET.search}}"</p>
{% endif %}

{% include 'games/components/cards_list.html' %}

{% endblock %}