GamesHaven/GamesHaven/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("games/", include("games.urls")),
    path("publishers/", include("publishers.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

GamesHaven/games/urls.py
from django.urls import path
from . import views


app_name = "games"

urlpatterns = [
    path("create/", views.create_game_view, name="create_game_view"),
    path("detail/<game_id>/", views.game_detail_view, name="game_detail_view"),
    path("update/<game_id>/", views.game_update_view, name="game_update_view"),
    path("delete/<game_id>/", views.game_delete_view, name="game_delete_view"),
    path("all/", views.all_games_view, name="all_games_view"),
    path("search/", views.search_games_view, name="search_games_view"),
    path("add_review/<game_id>/", views.add_review_view, name="add_review_view"),
]

GamesHaven/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('contact/', views.contact_view, name="contact_view"),
    path("mode/<mode>/", views.mode_view, name="mode_view"),
    path("test/params/<int:param1>/<param2>/", views.test_params_view, name="test_params_view")
]

GamesHaven/main/models.py
from django.db import models

# Create your models here.

GamesHaven/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from games.models import Game

# Create your views here.

def home_view(request:HttpRequest):

    #get all games
    games = Game.objects.all().order_by("-release_date")[0:3]

    return render(request, 'main/index.html', {"games" : games} )


def contact_view(request:HttpRequest):

    return render(request, 'main/contact.html' )



def mode_view(request:HttpRequest, mode):

    response = redirect(request.GET.get("next", "/"))

    if mode == "light":
        response.set_cookie("mode", "light")
    elif mode == "dark":
        response.set_cookie("mode", "dark")


    return response



def test_params_view(request:HttpRequest, param1, param2):

    print(param1, param2)

    if "query_param1" in request.GET:
        query_param1 = request.GET["query_param1"]
        print("Query Parameter 1", query_param1)

    return render(request, "main/test_params.html", {"param1" : param1})

GamesHaven/main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Gamers Haven{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bungee&family=Odibee+Sans&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
  <style>


  </style>
  </head>
  <body  {% if "mode" in request.COOKIES and request.COOKIES.mode == "dark" %} class="dark" {% endif %}>

    <div class="container-fluid sticky-top  bg-dark pt-4 pb-4">
    <nav class="navbar navbar-expand-lg navbar-dark top-nav" aria-label="Eighth navbar example">
      <div class="container">
        <a class="navbar-brand" href="/"><h2 class="top-logo">Games.Haven</h2></a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse justify-content-end" id="navbarsExample07">
          <ul class="navbar-nav mb-2 mb-lg-0 d-flex gap-4 align-items-center">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:contact_view' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'games:create_game_view' %}" >New Game</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" >About</a>
            </li>
            <li class="nav-item">
              <div class="display-mode d-flex align-items-center gap-1">    
                <a href="{% url 'main:mode_view' 'light' %}?next={{request.path}}" class="nav-link"><span class="material-symbols-outlined {% if 'mode' not in request.COOKIES or 'mode' in request.COOKIES and request.COOKIES.mode != 'dark' %} active-icon {% endif %}">light_mode</span></a>
                <a href="{% url 'main:mode_view' 'dark' %}?next={{request.path}}" class="nav-link"><span class="material-symbols-outlined {% if 'mode' in request.COOKIES and request.COOKIES.mode == 'dark' %} active-icon {% endif %}">dark_mode</span></a>
              </div>
            </li>

            <form role="search" method="get" action="{% url 'games:search_games_view' %}">
              <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="search" value="{{request.GET.search}}" required minlength="3">
            </form>
          </ul>

        </div>
      </div>
    </nav>
  </div>
    
    <main class="container  mt-4">
    {% block content %}
    {% endblock %}
    </main>


    <div class="container">
      <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
        <div class="col mb-3">
            <a class="navbar-brand" href="/"><h2 class="top-logo">Games.Haven</h2></a>
          <p class="text-muted">© 2024</p>
        </div>
    
        <div class="col mb-3">
    
        </div>
    
        <div class="col mb-3">
          <h5>Section</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
          </ul>
        </div>
    
        <div class="col mb-3">
          <h5>Section</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
          </ul>
        </div>
    
        <div class="col mb-3">
          <h5>Section</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
          </ul>
        </div>
      </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

GamesHaven/main/templates/main/contact.html
{% extends 'main/base.html' %}


{% block content %}
<div class="row row-cols-1 row-cols-md-2">
    
    <div class="col  pt-3">
        <h1>Contact Us</h1>
        <h4>Telephone: <a href="tel:+966562736534">+966 57263883764</a></h2>
        <h4>Email: <a href="mailto:info@realeastate.com">info@realeastate.com</a></h2>
        <h4>Address:</h2>
        <p>Anas bin Malik, Riyadh
           Building W-112
           Saudi Arabia
        </p>


    </div>

    <div class="col  pt-3">

        <iframe class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7242.148207477835!2d46.727640483143794!3d24.827139294372518!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e2efc6d472d42af%3A0x24b3a53de9cbc5c3!2z2KjYp9ix2YMg2KfZgdmG2YrZiCDZhdmI2YQ!5e0!3m2!1sar!2ssa!4v1699862202453!5m2!1sar!2ssa" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

        
    </div>

</div>
{% endblock %}

GamesHaven/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %} Gamers Haven {% endblock %}

{% block content %}



<div class="row   row-cols-1 row-cols-md-2  hero-row">
    <div class="col order-2 order-md-1 ">
        <div class="d-flex flex-column justify-content-center align-items-center h-100">
            <h1 class="text-center">The Place for Gamers!</h1>
            <h3 class="text-center">For all the games information you need</h3>
        </div>

    </div>

    <div class="col order-1 overflow-hidden hero h-100 p-0">
        <!-- <img class="w-100 h-100 object-fit-cover" src="https://static0.srcdn.com/wordpress/wp-content/uploads/2023/11/greatest-movies-of-all-time.jpg" /> -->
        <div class="vid-container">
          <video class="h-100" src="/static/videos/backvid.mp4" muted autoplay loop></video>
        </div>
    </div>
</div>

<hr />
<a href="{% url 'games:all_games_view' %}">
<div class="d-flex align-items-center justify-content-between ">
  <h2 class="m-0 p-0">Latest Games</h2>
  <span class="material-symbols-outlined text-fxl">arrow_forward</span>
</div>
</a>

{% include 'games/components/cards_list.html' %}

</div>

{% endblock %}

GamesHaven/main/templates/main/test_params.html
{% extends 'main/base.html' %}


{% block content %}
<div class="row row-cols-1 row-cols-md-2">
    
    <div class="col  pt-3">
        <h1>Testing path & query parameters</h1>
        <h2>{{param1}}</h2>

    </div>

</div>
{% endblock %}